/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up-new` | `/sign-up-new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/budget` | `/budget`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/expenses` | `/expenses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/income` | `/income`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/lib/auth`; params?: Router.UnknownInputParams; } | { pathname: `/utils/constant`; params?: Router.UnknownInputParams; } | { pathname: `/utils/dateUtils`; params?: Router.UnknownInputParams; } | { pathname: `/utils/theme`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up-new` | `/sign-up-new`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/budget` | `/budget`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/expenses` | `/expenses`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/income` | `/income`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/constant`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/dateUtils`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/theme`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up-new${`?${string}` | `#${string}` | ''}` | `/sign-up-new${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}${'/(tabs)'}/budget${`?${string}` | `#${string}` | ''}` | `/budget${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}${'/(tabs)'}/expenses${`?${string}` | `#${string}` | ''}` | `/expenses${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}${'/(tabs)'}/income${`?${string}` | `#${string}` | ''}` | `/income${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/lib/auth${`?${string}` | `#${string}` | ''}` | `/utils/constant${`?${string}` | `#${string}` | ''}` | `/utils/dateUtils${`?${string}` | `#${string}` | ''}` | `/utils/theme${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up-new` | `/sign-up-new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/budget` | `/budget`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/expenses` | `/expenses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/income` | `/income`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/lib/auth`; params?: Router.UnknownInputParams; } | { pathname: `/utils/constant`; params?: Router.UnknownInputParams; } | { pathname: `/utils/dateUtils`; params?: Router.UnknownInputParams; } | { pathname: `/utils/theme`; params?: Router.UnknownInputParams; };
    }
  }
}
